openapi: 3.1.0
info:
  title: OpenSearch UBI API
  description: OpenSearch UBI API.
  version: 1.0.0
paths:
  /_plugins/ubi/initialize:
    get:
      operationId: ubi.initialize.0
      x-operation-group: ubi.initialize
      x-version-added: '1.0'
      description: Initializes the UBI indexes.
      responses:
        '200':
          $ref: '#/components/responses/ubi.initialize@200'

components:
  responses:
    ubi.initialize@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ubi._common.yaml#/components/schemas/Initialize'
